basic:
  image_tag_version: "latest"
  controller_image_name: "volcanosh/volcano-controllers"
  scheduler_image_name: "volcanosh/volcano-scheduler"
  admission_image_name: "volcanosh/volcano-admission"
  admission_secret_name: "volcano-admission-secret"
  image_pull_secret: ""
